---
- hosts: 172.31.39.85
  become: yes
  tasks:
  - name: i want to execute linux command directly by playbook
    command: hostname -f
    register: myresult
  - name: i want to display my first task result
    debug:
      msg: "{{myresult}}"

  - name: install git
    apt:
     name: git
     state: present
    when: myresult.stderr ==""

  - name: install tree
    apt: 
     name: tree 
     state: present
    when: myresult.stderr !=""