---
- hosts: 172.31.39.85
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: i want to install webserver on ansible node 
    apt:
     name: apache2
     state: present

  - name: i want copy myindex file into ansible node side
    template:
       src: myindex.j2
       dest: /var/www/html/index.html

  - name: i want to download remote file
    get_url:
      url: https://get.jenkins.io/war-stable/2.332.3/jenkins.war
      dest: /home/ubuntu/jenkins.war
      force_basic_auth: yes