---
- hosts: 172.31.39.85
  become: yes
  vars:
    myvar1: git
    myvar2: tree
    myvar3: wget
  tasks:
  - name: install tree 
    apt: 
     name: "{{myvar1}}"
  - name: i want to display myvar1
    debug:
      msg: "{{myvar1}}"