---
- hosts: all
  become: yes
  tasks:
   - name: i want to install webserver on ansible ubuntu node
     apt:
      name: apache2
      state: present
     when: ansible_os_family =="Debian" 
   - name: i want to start webserver on ansible ubuntu node
     service: 
      name: apache2 
      state: started
     when: ansible_os-family =="Debian"
